### PR TITLE
Feature/upgrade 2.0

### PR DESCRIPTION
**Pull request by tvdijen**
Upgrades this module to SSP 2.0 (still in RC-state)
Since I don't use DUO, I wasn't able to test things...

### CODE REVIEW

**Comment by kenyonit** [comment]
Hi Tim,

I have Duo and can help with testing... module is enabled and get the following when duo is called:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 public\_include.php:28 (SimpleSAML_exception_handler)
1 vendor\symfony\error-handler\ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Exception: Could not resolve 'duouniversal:DuoUniversal': The class 'SimpleSAML\Module\duouniversal\Auth\Process\DuoUniversal' isn't a subclass of '\SimpleSAML\Auth\ProcessingFilter'.
Backtrace:
16 src\SimpleSAML\Module.php:459 (SimpleSAML\Module::resolveClass)
15 src\SimpleSAML\Auth\ProcessingChain.php:158 (SimpleSAML\Auth\ProcessingChain::parseFilter)
14 src\SimpleSAML\Auth\ProcessingChain.php:134 (SimpleSAML\Auth\ProcessingChain::parseFilterList)
13 src\SimpleSAML\Auth\ProcessingChain.php:67 (SimpleSAML\Auth\ProcessingChain::__construct)
12 src\SimpleSAML\IdP.php:320 (SimpleSAML\IdP::postAuth)
11 [builtin] (call_user_func)
10 src\SimpleSAML\Auth\Source.php:232 (SimpleSAML\Auth\Source::loginCompleted)
9 [builtin] (call_user_func)
8 src\SimpleSAML\Auth\Source.php:153 (SimpleSAML\Auth\Source::completeAuth)
7 modules\core\src\Auth\UserPassBase.php:317 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
6 modules\core\src\Controller\Login.php:226 (SimpleSAML\Module\core\Controller\Login::handleLogin)
5 modules\core\src\Controller\Login.php:124 (SimpleSAML\Module\core\Controller\Login::loginuserpass)
4 vendor\symfony\http-kernel\HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor\symfony\http-kernel\HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor\symfony\http-kernel\Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src\SimpleSAML\Module.php:234 (SimpleSAML\Module::process)
0 public\module.php:14 (N/A)

**Comment by tvdijen** [comment]
I see I had missed a few spots. Can you try again @kenyonit ?

**Comment by kenyonit** [comment]
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 public\_include.php:28 (SimpleSAML_exception_handler)
1 vendor\symfony\error-handler\ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: SimpleSAML\Module\saml\Error: Responder: SimpleSAML\Error\UnserializableException: Could not resolve 'duouniversal:DuoUniversal': The class 'SimpleSAML\Module\duouniversal\Auth\Process\DuoUniversal' isn't a subclass of '\SimpleSAML\Auth\ProcessingFilter'.
Backtrace:
7 modules\saml\src\Message.php:454 (SimpleSAML\Module\saml\Message::getResponseError)
6 modules\saml\src\Message.php:590 (SimpleSAML\Module\saml\Message::processResponse)
5 modules\saml\src\Controller\ServiceProvider.php:316 (SimpleSAML\Module\saml\Controller\ServiceProvider::assertionConsumerService)
4 vendor\symfony\http-kernel\HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor\symfony\http-kernel\HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor\symfony\http-kernel\Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src\SimpleSAML\Module.php:234 (SimpleSAML\Module::process)
0 public\module.php:14 (N/A)

**Comment by tvdijen** [comment]
I don't think you can properly test it without merging it first.
There is no way to install this PR using composer, so the classes are not properly autoloaded.

If you could create a new branch, we can merge this work there and properly install it using composer.

**Comment by kenyonit** [comment]
@0x0fbc can you assist here? Thanks

**Comment by 0x0fbc** [comment]
Sorry for the radio silence -

There is a way to install a PR like this using a path repository entry in composer.json that I've been using to test installing with the module installer. I'll leave instructions at the bottom of this. 

Anyway, I installed the module in a test IdP running SSP 2.0.4 and tried everything out. Found an issue where the old callback URL was being sent to Duo's API, and another where the new callback controller's class wasn't being resolved. I added some commits to the PR (with messed up author info, my bad) that fixes them. With those changes, everything seems to be working great! As requested, I created a `feature/upgrade-2.0` branch on this repo and will merge this PR into it to test a full end-to-end installation using Composer, the module installer, and Packagist. 

Thank you, @tvdijen, for jumping in and updating this module for SSP 2.0!!

----

Composer local module installation:

Clone the repo & checkout the PR's branch: 
`git clone -b "feature/upgrade-2.0" https://github.com/tvdijen/simplesamlphp-module-duouniversal.git`

Add a path repository pointing to the cloned repo in `simplesamlphp/composer.json`:
```
"repositories": [
    {
            "type": "path",
            "url": "/path/to/cloned/simplesamlphp-module-duouniversal",
            "options": { "symlink": false }
    }
],
```
Require the module with version `@dev`, and Composer will install it from the local directory using the module installer:
`$ composer require "0x0fbc/simplesamlphp-module-duouniversal @dev"`

**Comment by tvdijen** [comment]
I found out it should even be possible to directly get the repo from Github without downloading it first;

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/0x0fbc/simplesamlphp-module-duouniversal"
        }
    ],
```

**Comment by kenyonit** [comment]
Thanks @0x0fbc  & @tvdijen 

I've setup a test instance and done some testing, getting an error when its attempting to save to the data store.

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 public\_include.php:31 (SimpleSAML_exception_handler)
1 vendor\symfony\error-handler\ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Error: Call to a member function set() on bool
Backtrace:
14 modules\duouniversal\src\Auth\Process\DuoUniversal.php:173 (SimpleSAML\Module\duouniversal\Auth\Process\DuoUniversal::process)
13 src\SimpleSAML\Auth\ProcessingChain.php:200 (SimpleSAML\Auth\ProcessingChain::processState)
12 src\SimpleSAML\IdP.php:326 (SimpleSAML\IdP::postAuth)
11 [builtin] (call_user_func)
10 src\SimpleSAML\Auth\Source.php:232 (SimpleSAML\Auth\Source::loginCompleted)
9 [builtin] (call_user_func)
8 src\SimpleSAML\Auth\Source.php:153 (SimpleSAML\Auth\Source::completeAuth)
7 modules\core\src\Auth\UserPassBase.php:317 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
6 modules\core\src\Controller\Login.php:226 (SimpleSAML\Module\core\Controller\Login::handleLogin)
5 modules\core\src\Controller\Login.php:124 (SimpleSAML\Module\core\Controller\Login::loginuserpass)
4 vendor\symfony\http-kernel\HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor\symfony\http-kernel\HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor\symfony\http-kernel\Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src\SimpleSAML\Module.php:234 (SimpleSAML\Module::process)
0 public\module.php:14 (N/A)

**Comment by tvdijen** [comment]
I don't understand how this can lead to a boolean in line 173

**Comment by 0x0fbc** [comment]
It looks like `StoreFactory::getInstance()` sets `StoreFactory`'s instance to `false` and returns it when `'phpsession'` is passed in. The module grabs `'store.type'` from config.php and it defaults to `'phpsession'`. I'll add code to throw an exception if the store instance comes back as false and add a note to the readme that a non-phpsession store is required. 

@kenyonit Can you try setting up one of the other session store options for your test instance? Memcached is pretty straightforward to install and configure. SSP has info on configuring the different stores here: https://simplesamlphp.org/docs/stable/simplesamlphp-maintenance.html#session-management

**Comment by tvdijen** [comment]
~~That doesn't make sense.. It should work just fine with phpsession for a store..~~
Forget what I said. Setting a store other than phpsession will fix this

**Comment by kenyonit** [comment]
@0x0fbc Yes my test was using 'phpsession'
I'll try another store option and report back

**Comment by kenyonit** [comment]
@0x0fbc @tvdijen - Tested using store.type = sql, now appears to be working as expected, cheers!

**Pull request merged**
